=== joeloto/DAM/marcas/validacionesXML/alumnos.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre,apellidos,direccion,DNI,(hombre|mujer),asignaturas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion numero (15|22) #REQUIRED>
<!ATTLIST direccion piso CDATA #IMPLIED>
<!ATTLIST direccion puerta CDATA #IMPLIED>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT hombre EMPTY>
<!ELEMENT mujer EMPTY>
<!ATTLIST alumno codigo ID #REQUIRED>   
<!ELEMENT asignaturas (asignatura)+>
<!ELEMENT asignatura (nombre,codigo,horas)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT horas (#PCDATA)>

=== joeloto/DAM/marcas/validacionesXML/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE alumnos PUBLIC "public-id" "alumnos.dtd">
<alumnos>
</alumnos> -->
<?xml-model href="alumnos.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<alumnos>
    <alumno codigo="AB09">
        <nombre></nombre>
        <apellidos></apellidos>
        <direccion numero="15" puerta="J">Parada</direccion>
        <DNI>12345678A</DNI>
        <hombre></hombre>
        <asignaturas>
            <asignatura>
                <nombre></nombre>
                <codigo>SA90</codigo>
                <horas>1</horas>
            </asignatura>
            <asignatura>
                <nombre></nombre>
                <codigo>SA91</codigo>
                <horas>2</horas>
            </asignatura>
            <asignatura>
                <nombre></nombre>
                <codigo>SA11</codigo>
                <horas>3</horas>
            </asignatura>
        </asignaturas>
    </alumno>
    <alumno codigo="AB19">
        <nombre></nombre>
        <apellidos></apellidos>
        <direccion numero="22" puerta="Y"></direccion>
        <DNI>11234567D</DNI>
        <mujer></mujer>
        <asignaturas>
            <asignatura>
                <nombre></nombre>
                <codigo>AA11</codigo>
                <horas>4</horas>
            </asignatura>
            <asignatura>
                <nombre></nombre>
                <codigo>AA22</codigo>
                <horas>6</horas>
            </asignatura>
            <asignatura>
                <nombre></nombre>
                <codigo>AA66</codigo>
                <horas>5</horas>
            </asignatura>
        </asignaturas>
    </alumno>
</alumnos>
